package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalUser;
import org.linlinjava.internetmedical.db.domain.InternetmedicalUserExample;

public interface InternetmedicalUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int insert(InternetmedicalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    InternetmedicalUser selectOneByExample(InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    InternetmedicalUser selectOneByExampleSelective(@Param("example") InternetmedicalUserExample example, @Param("selective") InternetmedicalUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    List<InternetmedicalUser> selectByExampleSelective(@Param("example") InternetmedicalUserExample example, @Param("selective") InternetmedicalUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    List<InternetmedicalUser> selectByExample(InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    InternetmedicalUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    InternetmedicalUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    InternetmedicalUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalUser record, @Param("example") InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalUser record, @Param("example") InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}