package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalSearchHistory;
import org.linlinjava.internetmedical.db.domain.InternetmedicalSearchHistoryExample;

public interface InternetmedicalSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int insert(InternetmedicalSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    InternetmedicalSearchHistory selectOneByExample(InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    InternetmedicalSearchHistory selectOneByExampleSelective(@Param("example") InternetmedicalSearchHistoryExample example, @Param("selective") InternetmedicalSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    List<InternetmedicalSearchHistory> selectByExampleSelective(@Param("example") InternetmedicalSearchHistoryExample example, @Param("selective") InternetmedicalSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    List<InternetmedicalSearchHistory> selectByExample(InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    InternetmedicalSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    InternetmedicalSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    InternetmedicalSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalSearchHistory record, @Param("example") InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalSearchHistory record, @Param("example") InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}