package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalFeedback;
import org.linlinjava.internetmedical.db.domain.InternetmedicalFeedbackExample;

public interface InternetmedicalFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int insert(InternetmedicalFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    InternetmedicalFeedback selectOneByExample(InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    InternetmedicalFeedback selectOneByExampleSelective(@Param("example") InternetmedicalFeedbackExample example, @Param("selective") InternetmedicalFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    List<InternetmedicalFeedback> selectByExampleSelective(@Param("example") InternetmedicalFeedbackExample example, @Param("selective") InternetmedicalFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    List<InternetmedicalFeedback> selectByExample(InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    InternetmedicalFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    InternetmedicalFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    InternetmedicalFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalFeedback record, @Param("example") InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalFeedback record, @Param("example") InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}