package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalAd;
import org.linlinjava.internetmedical.db.domain.InternetmedicalAdExample;

public interface InternetmedicalAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int insert(InternetmedicalAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    InternetmedicalAd selectOneByExample(InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    InternetmedicalAd selectOneByExampleSelective(@Param("example") InternetmedicalAdExample example, @Param("selective") InternetmedicalAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    List<InternetmedicalAd> selectByExampleSelective(@Param("example") InternetmedicalAdExample example, @Param("selective") InternetmedicalAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    List<InternetmedicalAd> selectByExample(InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    InternetmedicalAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    InternetmedicalAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    InternetmedicalAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalAd record, @Param("example") InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalAd record, @Param("example") InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}