package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalOrderGoods;
import org.linlinjava.internetmedical.db.domain.InternetmedicalOrderGoodsExample;

public interface InternetmedicalOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int insert(InternetmedicalOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    InternetmedicalOrderGoods selectOneByExample(InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    InternetmedicalOrderGoods selectOneByExampleSelective(@Param("example") InternetmedicalOrderGoodsExample example, @Param("selective") InternetmedicalOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    List<InternetmedicalOrderGoods> selectByExampleSelective(@Param("example") InternetmedicalOrderGoodsExample example, @Param("selective") InternetmedicalOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    List<InternetmedicalOrderGoods> selectByExample(InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    InternetmedicalOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    InternetmedicalOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    InternetmedicalOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalOrderGoods record, @Param("example") InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalOrderGoods record, @Param("example") InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}