package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalAddress;
import org.linlinjava.internetmedical.db.domain.InternetmedicalAddressExample;

public interface InternetmedicalAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int insert(InternetmedicalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    InternetmedicalAddress selectOneByExample(InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    InternetmedicalAddress selectOneByExampleSelective(@Param("example") InternetmedicalAddressExample example, @Param("selective") InternetmedicalAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    List<InternetmedicalAddress> selectByExampleSelective(@Param("example") InternetmedicalAddressExample example, @Param("selective") InternetmedicalAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    List<InternetmedicalAddress> selectByExample(InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    InternetmedicalAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    InternetmedicalAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    InternetmedicalAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalAddress record, @Param("example") InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalAddress record, @Param("example") InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}