package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalFootprint;
import org.linlinjava.internetmedical.db.domain.InternetmedicalFootprintExample;

public interface InternetmedicalFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int insert(InternetmedicalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    InternetmedicalFootprint selectOneByExample(InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    InternetmedicalFootprint selectOneByExampleSelective(@Param("example") InternetmedicalFootprintExample example, @Param("selective") InternetmedicalFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    List<InternetmedicalFootprint> selectByExampleSelective(@Param("example") InternetmedicalFootprintExample example, @Param("selective") InternetmedicalFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    List<InternetmedicalFootprint> selectByExample(InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    InternetmedicalFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    InternetmedicalFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    InternetmedicalFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalFootprint record, @Param("example") InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalFootprint record, @Param("example") InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}