package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalComment;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCommentExample;

public interface InternetmedicalCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int insert(InternetmedicalComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    InternetmedicalComment selectOneByExample(InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    InternetmedicalComment selectOneByExampleSelective(@Param("example") InternetmedicalCommentExample example, @Param("selective") InternetmedicalComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    List<InternetmedicalComment> selectByExampleSelective(@Param("example") InternetmedicalCommentExample example, @Param("selective") InternetmedicalComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    List<InternetmedicalComment> selectByExample(InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    InternetmedicalComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    InternetmedicalComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    InternetmedicalComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalComment record, @Param("example") InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalComment record, @Param("example") InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}