package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalPermission;
import org.linlinjava.internetmedical.db.domain.InternetmedicalPermissionExample;

public interface InternetmedicalPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int insert(InternetmedicalPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    InternetmedicalPermission selectOneByExample(InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    InternetmedicalPermission selectOneByExampleSelective(@Param("example") InternetmedicalPermissionExample example, @Param("selective") InternetmedicalPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    List<InternetmedicalPermission> selectByExampleSelective(@Param("example") InternetmedicalPermissionExample example, @Param("selective") InternetmedicalPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    List<InternetmedicalPermission> selectByExample(InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    InternetmedicalPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    InternetmedicalPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    InternetmedicalPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalPermission record, @Param("example") InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalPermission record, @Param("example") InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}