package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalSystem;
import org.linlinjava.internetmedical.db.domain.InternetmedicalSystemExample;

public interface InternetmedicalSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int insert(InternetmedicalSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    InternetmedicalSystem selectOneByExample(InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    InternetmedicalSystem selectOneByExampleSelective(@Param("example") InternetmedicalSystemExample example, @Param("selective") InternetmedicalSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    List<InternetmedicalSystem> selectByExampleSelective(@Param("example") InternetmedicalSystemExample example, @Param("selective") InternetmedicalSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    List<InternetmedicalSystem> selectByExample(InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    InternetmedicalSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    InternetmedicalSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    InternetmedicalSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalSystem record, @Param("example") InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalSystem record, @Param("example") InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}