package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCollect;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCollectExample;

public interface InternetmedicalCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int insert(InternetmedicalCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    InternetmedicalCollect selectOneByExample(InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    InternetmedicalCollect selectOneByExampleSelective(@Param("example") InternetmedicalCollectExample example, @Param("selective") InternetmedicalCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    List<InternetmedicalCollect> selectByExampleSelective(@Param("example") InternetmedicalCollectExample example, @Param("selective") InternetmedicalCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    List<InternetmedicalCollect> selectByExample(InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    InternetmedicalCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    InternetmedicalCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    InternetmedicalCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalCollect record, @Param("example") InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalCollect record, @Param("example") InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}