package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCart;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCartExample;

public interface InternetmedicalCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int insert(InternetmedicalCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    InternetmedicalCart selectOneByExample(InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    InternetmedicalCart selectOneByExampleSelective(@Param("example") InternetmedicalCartExample example, @Param("selective") InternetmedicalCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    List<InternetmedicalCart> selectByExampleSelective(@Param("example") InternetmedicalCartExample example, @Param("selective") InternetmedicalCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    List<InternetmedicalCart> selectByExample(InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    InternetmedicalCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    InternetmedicalCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    InternetmedicalCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalCart record, @Param("example") InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalCart record, @Param("example") InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}