package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalDoctors;
import org.linlinjava.internetmedical.db.domain.InternetmedicalDoctorsExample;

public interface InternetmedicalDoctorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int insert(InternetmedicalDoctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalDoctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    InternetmedicalDoctors selectOneByExample(InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    InternetmedicalDoctors selectOneByExampleSelective(@Param("example") InternetmedicalDoctorsExample example, @Param("selective") InternetmedicalDoctors.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    List<InternetmedicalDoctors> selectByExampleSelective(@Param("example") InternetmedicalDoctorsExample example, @Param("selective") InternetmedicalDoctors.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    List<InternetmedicalDoctors> selectByExample(InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    InternetmedicalDoctors selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalDoctors.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    InternetmedicalDoctors selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    InternetmedicalDoctors selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalDoctors record, @Param("example") InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalDoctors record, @Param("example") InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalDoctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalDoctors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalDoctorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_doctors
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}