package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalAdmin;
import org.linlinjava.internetmedical.db.domain.InternetmedicalAdminExample;

public interface InternetmedicalAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int insert(InternetmedicalAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    InternetmedicalAdmin selectOneByExample(InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    InternetmedicalAdmin selectOneByExampleSelective(@Param("example") InternetmedicalAdminExample example, @Param("selective") InternetmedicalAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    List<InternetmedicalAdmin> selectByExampleSelective(@Param("example") InternetmedicalAdminExample example, @Param("selective") InternetmedicalAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    List<InternetmedicalAdmin> selectByExample(InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    InternetmedicalAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    InternetmedicalAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    InternetmedicalAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalAdmin record, @Param("example") InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalAdmin record, @Param("example") InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}