package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalOrder;
import org.linlinjava.internetmedical.db.domain.InternetmedicalOrderExample;

public interface InternetmedicalOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int insert(InternetmedicalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    InternetmedicalOrder selectOneByExample(InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    InternetmedicalOrder selectOneByExampleSelective(@Param("example") InternetmedicalOrderExample example, @Param("selective") InternetmedicalOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    List<InternetmedicalOrder> selectByExampleSelective(@Param("example") InternetmedicalOrderExample example, @Param("selective") InternetmedicalOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    List<InternetmedicalOrder> selectByExample(InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    InternetmedicalOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    InternetmedicalOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    InternetmedicalOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalOrder record, @Param("example") InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalOrder record, @Param("example") InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}