package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalPatientinfo;
import org.linlinjava.internetmedical.db.domain.InternetmedicalPatientinfoExample;

public interface InternetmedicalPatientinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int insert(InternetmedicalPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    InternetmedicalPatientinfo selectOneByExample(InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    InternetmedicalPatientinfo selectOneByExampleSelective(@Param("example") InternetmedicalPatientinfoExample example, @Param("selective") InternetmedicalPatientinfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    List<InternetmedicalPatientinfo> selectByExampleSelective(@Param("example") InternetmedicalPatientinfoExample example, @Param("selective") InternetmedicalPatientinfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    List<InternetmedicalPatientinfo> selectByExample(InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    InternetmedicalPatientinfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalPatientinfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    InternetmedicalPatientinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    InternetmedicalPatientinfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalPatientinfo record, @Param("example") InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalPatientinfo record, @Param("example") InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalPatientinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalPatientinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}