package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalKeyword;
import org.linlinjava.internetmedical.db.domain.InternetmedicalKeywordExample;

public interface InternetmedicalKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int insert(InternetmedicalKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    InternetmedicalKeyword selectOneByExample(InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    InternetmedicalKeyword selectOneByExampleSelective(@Param("example") InternetmedicalKeywordExample example, @Param("selective") InternetmedicalKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    List<InternetmedicalKeyword> selectByExampleSelective(@Param("example") InternetmedicalKeywordExample example, @Param("selective") InternetmedicalKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    List<InternetmedicalKeyword> selectByExample(InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    InternetmedicalKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    InternetmedicalKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    InternetmedicalKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalKeyword record, @Param("example") InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalKeyword record, @Param("example") InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}