package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalGoodsProduct;
import org.linlinjava.internetmedical.db.domain.InternetmedicalGoodsProductExample;

public interface InternetmedicalGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int insert(InternetmedicalGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    InternetmedicalGoodsProduct selectOneByExample(InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    InternetmedicalGoodsProduct selectOneByExampleSelective(@Param("example") InternetmedicalGoodsProductExample example, @Param("selective") InternetmedicalGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    List<InternetmedicalGoodsProduct> selectByExampleSelective(@Param("example") InternetmedicalGoodsProductExample example, @Param("selective") InternetmedicalGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    List<InternetmedicalGoodsProduct> selectByExample(InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    InternetmedicalGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    InternetmedicalGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    InternetmedicalGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalGoodsProduct record, @Param("example") InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalGoodsProduct record, @Param("example") InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}