package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalTopic;
import org.linlinjava.internetmedical.db.domain.InternetmedicalTopicExample;

public interface InternetmedicalTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int insert(InternetmedicalTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    InternetmedicalTopic selectOneByExample(InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    InternetmedicalTopic selectOneByExampleSelective(@Param("example") InternetmedicalTopicExample example, @Param("selective") InternetmedicalTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    InternetmedicalTopic selectOneByExampleWithBLOBs(InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    List<InternetmedicalTopic> selectByExampleSelective(@Param("example") InternetmedicalTopicExample example, @Param("selective") InternetmedicalTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    List<InternetmedicalTopic> selectByExampleWithBLOBs(InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    List<InternetmedicalTopic> selectByExample(InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    InternetmedicalTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    InternetmedicalTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    InternetmedicalTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalTopic record, @Param("example") InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") InternetmedicalTopic record, @Param("example") InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalTopic record, @Param("example") InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(InternetmedicalTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}