package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalIssue;
import org.linlinjava.internetmedical.db.domain.InternetmedicalIssueExample;

public interface InternetmedicalIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int insert(InternetmedicalIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    InternetmedicalIssue selectOneByExample(InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    InternetmedicalIssue selectOneByExampleSelective(@Param("example") InternetmedicalIssueExample example, @Param("selective") InternetmedicalIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    List<InternetmedicalIssue> selectByExampleSelective(@Param("example") InternetmedicalIssueExample example, @Param("selective") InternetmedicalIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    List<InternetmedicalIssue> selectByExample(InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    InternetmedicalIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    InternetmedicalIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    InternetmedicalIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalIssue record, @Param("example") InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalIssue record, @Param("example") InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}