package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCategory;
import org.linlinjava.internetmedical.db.domain.InternetmedicalCategoryExample;

public interface InternetmedicalCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int insert(InternetmedicalCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    InternetmedicalCategory selectOneByExample(InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    InternetmedicalCategory selectOneByExampleSelective(@Param("example") InternetmedicalCategoryExample example, @Param("selective") InternetmedicalCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    List<InternetmedicalCategory> selectByExampleSelective(@Param("example") InternetmedicalCategoryExample example, @Param("selective") InternetmedicalCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    List<InternetmedicalCategory> selectByExample(InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    InternetmedicalCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    InternetmedicalCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    InternetmedicalCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalCategory record, @Param("example") InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalCategory record, @Param("example") InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}