package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalBrand;
import org.linlinjava.internetmedical.db.domain.InternetmedicalBrandExample;

public interface InternetmedicalBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int insert(InternetmedicalBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    InternetmedicalBrand selectOneByExample(InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    InternetmedicalBrand selectOneByExampleSelective(@Param("example") InternetmedicalBrandExample example, @Param("selective") InternetmedicalBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    List<InternetmedicalBrand> selectByExampleSelective(@Param("example") InternetmedicalBrandExample example, @Param("selective") InternetmedicalBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    List<InternetmedicalBrand> selectByExample(InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    InternetmedicalBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    InternetmedicalBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    InternetmedicalBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalBrand record, @Param("example") InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalBrand record, @Param("example") InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}