package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalNotice;
import org.linlinjava.internetmedical.db.domain.InternetmedicalNoticeExample;

public interface InternetmedicalNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int insert(InternetmedicalNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    InternetmedicalNotice selectOneByExample(InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    InternetmedicalNotice selectOneByExampleSelective(@Param("example") InternetmedicalNoticeExample example, @Param("selective") InternetmedicalNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    List<InternetmedicalNotice> selectByExampleSelective(@Param("example") InternetmedicalNoticeExample example, @Param("selective") InternetmedicalNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    List<InternetmedicalNotice> selectByExample(InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    InternetmedicalNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    InternetmedicalNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    InternetmedicalNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalNotice record, @Param("example") InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalNotice record, @Param("example") InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}