package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalStorage;
import org.linlinjava.internetmedical.db.domain.InternetmedicalStorageExample;

public interface InternetmedicalStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int insert(InternetmedicalStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    InternetmedicalStorage selectOneByExample(InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    InternetmedicalStorage selectOneByExampleSelective(@Param("example") InternetmedicalStorageExample example, @Param("selective") InternetmedicalStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    List<InternetmedicalStorage> selectByExampleSelective(@Param("example") InternetmedicalStorageExample example, @Param("selective") InternetmedicalStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    List<InternetmedicalStorage> selectByExample(InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    InternetmedicalStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    InternetmedicalStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    InternetmedicalStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalStorage record, @Param("example") InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalStorage record, @Param("example") InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}