package org.linlinjava.internetmedical.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.internetmedical.db.domain.InternetmedicalGrouponRules;
import org.linlinjava.internetmedical.db.domain.InternetmedicalGrouponRulesExample;

public interface InternetmedicalGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int insert(InternetmedicalGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(InternetmedicalGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    InternetmedicalGrouponRules selectOneByExample(InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    InternetmedicalGrouponRules selectOneByExampleSelective(@Param("example") InternetmedicalGrouponRulesExample example, @Param("selective") InternetmedicalGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    List<InternetmedicalGrouponRules> selectByExampleSelective(@Param("example") InternetmedicalGrouponRulesExample example, @Param("selective") InternetmedicalGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    List<InternetmedicalGrouponRules> selectByExample(InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    InternetmedicalGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") InternetmedicalGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    InternetmedicalGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    InternetmedicalGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InternetmedicalGrouponRules record, @Param("example") InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InternetmedicalGrouponRules record, @Param("example") InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InternetmedicalGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InternetmedicalGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") InternetmedicalGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}