package org.linlinjava.internetmedical.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class InternetmedicalPatientinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.bmi
     *
     * @mbg.generated
     */
    private Integer bmi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.smoke
     *
     * @mbg.generated
     */
    private Boolean smoke;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.drink
     *
     * @mbg.generated
     */
    private Boolean drink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.marry
     *
     * @mbg.generated
     */
    private Boolean marry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.child
     *
     * @mbg.generated
     */
    private Boolean child;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.chronic
     *
     * @mbg.generated
     */
    private Boolean chronic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.allergy
     *
     * @mbg.generated
     */
    private Boolean allergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.history
     *
     * @mbg.generated
     */
    private String history;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internetmedical_patientinfo.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.id
     *
     * @return the value of internetmedical_patientinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.id
     *
     * @param id the value for internetmedical_patientinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.user_id
     *
     * @return the value of internetmedical_patientinfo.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.user_id
     *
     * @param userId the value for internetmedical_patientinfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.name
     *
     * @return the value of internetmedical_patientinfo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.name
     *
     * @param name the value for internetmedical_patientinfo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.age
     *
     * @return the value of internetmedical_patientinfo.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.age
     *
     * @param age the value for internetmedical_patientinfo.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.height
     *
     * @return the value of internetmedical_patientinfo.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.height
     *
     * @param height the value for internetmedical_patientinfo.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.weight
     *
     * @return the value of internetmedical_patientinfo.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.weight
     *
     * @param weight the value for internetmedical_patientinfo.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.bmi
     *
     * @return the value of internetmedical_patientinfo.bmi
     *
     * @mbg.generated
     */
    public Integer getBmi() {
        return bmi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.bmi
     *
     * @param bmi the value for internetmedical_patientinfo.bmi
     *
     * @mbg.generated
     */
    public void setBmi(Integer bmi) {
        this.bmi = bmi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.smoke
     *
     * @return the value of internetmedical_patientinfo.smoke
     *
     * @mbg.generated
     */
    public Boolean getSmoke() {
        return smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.smoke
     *
     * @param smoke the value for internetmedical_patientinfo.smoke
     *
     * @mbg.generated
     */
    public void setSmoke(Boolean smoke) {
        this.smoke = smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.drink
     *
     * @return the value of internetmedical_patientinfo.drink
     *
     * @mbg.generated
     */
    public Boolean getDrink() {
        return drink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.drink
     *
     * @param drink the value for internetmedical_patientinfo.drink
     *
     * @mbg.generated
     */
    public void setDrink(Boolean drink) {
        this.drink = drink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.marry
     *
     * @return the value of internetmedical_patientinfo.marry
     *
     * @mbg.generated
     */
    public Boolean getMarry() {
        return marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.marry
     *
     * @param marry the value for internetmedical_patientinfo.marry
     *
     * @mbg.generated
     */
    public void setMarry(Boolean marry) {
        this.marry = marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.child
     *
     * @return the value of internetmedical_patientinfo.child
     *
     * @mbg.generated
     */
    public Boolean getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.child
     *
     * @param child the value for internetmedical_patientinfo.child
     *
     * @mbg.generated
     */
    public void setChild(Boolean child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.chronic
     *
     * @return the value of internetmedical_patientinfo.chronic
     *
     * @mbg.generated
     */
    public Boolean getChronic() {
        return chronic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.chronic
     *
     * @param chronic the value for internetmedical_patientinfo.chronic
     *
     * @mbg.generated
     */
    public void setChronic(Boolean chronic) {
        this.chronic = chronic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.allergy
     *
     * @return the value of internetmedical_patientinfo.allergy
     *
     * @mbg.generated
     */
    public Boolean getAllergy() {
        return allergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.allergy
     *
     * @param allergy the value for internetmedical_patientinfo.allergy
     *
     * @mbg.generated
     */
    public void setAllergy(Boolean allergy) {
        this.allergy = allergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.desc
     *
     * @return the value of internetmedical_patientinfo.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.desc
     *
     * @param desc the value for internetmedical_patientinfo.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.history
     *
     * @return the value of internetmedical_patientinfo.history
     *
     * @mbg.generated
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.history
     *
     * @param history the value for internetmedical_patientinfo.history
     *
     * @mbg.generated
     */
    public void setHistory(String history) {
        this.history = history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.add_time
     *
     * @return the value of internetmedical_patientinfo.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.add_time
     *
     * @param addTime the value for internetmedical_patientinfo.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.update_time
     *
     * @return the value of internetmedical_patientinfo.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.update_time
     *
     * @param updateTime the value for internetmedical_patientinfo.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internetmedical_patientinfo.deleted
     *
     * @return the value of internetmedical_patientinfo.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internetmedical_patientinfo.deleted
     *
     * @param deleted the value for internetmedical_patientinfo.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", height=").append(height);
        sb.append(", weight=").append(weight);
        sb.append(", bmi=").append(bmi);
        sb.append(", smoke=").append(smoke);
        sb.append(", drink=").append(drink);
        sb.append(", marry=").append(marry);
        sb.append(", child=").append(child);
        sb.append(", chronic=").append(chronic);
        sb.append(", allergy=").append(allergy);
        sb.append(", desc=").append(desc);
        sb.append(", history=").append(history);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InternetmedicalPatientinfo other = (InternetmedicalPatientinfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getHeight() == null ? other.getHeight() == null : this.getHeight().equals(other.getHeight()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getBmi() == null ? other.getBmi() == null : this.getBmi().equals(other.getBmi()))
            && (this.getSmoke() == null ? other.getSmoke() == null : this.getSmoke().equals(other.getSmoke()))
            && (this.getDrink() == null ? other.getDrink() == null : this.getDrink().equals(other.getDrink()))
            && (this.getMarry() == null ? other.getMarry() == null : this.getMarry().equals(other.getMarry()))
            && (this.getChild() == null ? other.getChild() == null : this.getChild().equals(other.getChild()))
            && (this.getChronic() == null ? other.getChronic() == null : this.getChronic().equals(other.getChronic()))
            && (this.getAllergy() == null ? other.getAllergy() == null : this.getAllergy().equals(other.getAllergy()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getHistory() == null ? other.getHistory() == null : this.getHistory().equals(other.getHistory()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getBmi() == null) ? 0 : getBmi().hashCode());
        result = prime * result + ((getSmoke() == null) ? 0 : getSmoke().hashCode());
        result = prime * result + ((getDrink() == null) ? 0 : getDrink().hashCode());
        result = prime * result + ((getMarry() == null) ? 0 : getMarry().hashCode());
        result = prime * result + ((getChild() == null) ? 0 : getChild().hashCode());
        result = prime * result + ((getChronic() == null) ? 0 : getChronic().hashCode());
        result = prime * result + ((getAllergy() == null) ? 0 : getAllergy().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getHistory() == null) ? 0 : getHistory().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table internetmedical_patientinfo
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        age("age", "age", "INTEGER", false),
        height("height", "height", "INTEGER", false),
        weight("weight", "weight", "INTEGER", false),
        bmi("bmi", "bmi", "INTEGER", false),
        smoke("smoke", "smoke", "BIT", false),
        drink("drink", "drink", "BIT", false),
        marry("marry", "marry", "BIT", false),
        child("child", "child", "BIT", false),
        chronic("chronic", "chronic", "BIT", false),
        allergy("allergy", "allergy", "BIT", false),
        desc("desc", "desc", "VARCHAR", true),
        history("history", "history", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table internetmedical_patientinfo
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}